/* Generated by Yosys 0.58+162 (git sha1 5d0847f6f, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* dynports =  1  *)
(* hdlname = "cpreg" *)
(* src = "../MODEL\\library_modules.v:1.1-88.10" *)
module \$paramod\cpreg\WIDTH=s32'00000000000000000000000000001011 (i_CLK, i_RSTn, i_READY, i_VALID, o_READY, o_VALID, i_D, o_Q);
  (* src = "../MODEL\\library_modules.v:6.16-6.21" *)
  input i_CLK;
  wire i_CLK;
  (* src = "../MODEL\\library_modules.v:7.16-7.22" *)
  input i_RSTn;
  wire i_RSTn;
  (* src = "../MODEL\\library_modules.v:8.16-8.23" *)
  input i_READY;
  wire i_READY;
  (* src = "../MODEL\\library_modules.v:8.25-8.32" *)
  input i_VALID;
  wire i_VALID;
  (* src = "../MODEL\\library_modules.v:9.16-9.23" *)
  output o_READY;
  wire o_READY;
  (* src = "../MODEL\\library_modules.v:9.25-9.32" *)
  output o_VALID;
  wire o_VALID;
  (* src = "../MODEL\\library_modules.v:10.30-10.33" *)
  input [10:0] i_D;
  wire [10:0] i_D;
  (* src = "../MODEL\\library_modules.v:11.30-11.33" *)
  output [10:0] o_Q;
  reg [10:0] o_Q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "../MODEL\\library_modules.v:6.16-6.21" *)
  wire _14_;
  (* src = "../MODEL\\library_modules.v:8.16-8.23" *)
  wire _15_;
  (* src = "../MODEL\\library_modules.v:8.25-8.32" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "../MODEL\\library_modules.v:9.16-9.23" *)
  wire _30_;
  (* src = "../MODEL\\library_modules.v:9.25-9.32" *)
  wire _31_;
  (* src = "../MODEL\\library_modules.v:53.43-53.43|../MODEL\\library_modules.v:45.13-63.20|D:\\programyMain\\yosys\\oss-cad-suite\\bin\\../share/yosys/techmap.v:583.21-583.22" *)
  wire _32_;
  (* src = "../MODEL\\library_modules.v:53.43-53.43|../MODEL\\library_modules.v:45.13-63.20|D:\\programyMain\\yosys\\oss-cad-suite\\bin\\../share/yosys/techmap.v:583.21-583.22" *)
  wire _33_;
  (* src = "../MODEL\\library_modules.v:16.10-16.15" *)
  wire _34_;
  (* src = "../MODEL\\library_modules.v:16.17-16.22" *)
  wire _35_;
  (* src = "../MODEL\\library_modules.v:15.18-15.25" *)
  wire _36_;
  (* src = "../MODEL\\library_modules.v:17.15-17.22" *)
  wire _37_;
  (* src = "../MODEL\\library_modules.v:17.15-17.22" *)
  wire _38_;
  (* force_downto = 32'd1 *)
  (* src = "../MODEL\\library_modules.v:53.43-53.43|../MODEL\\library_modules.v:45.13-63.20|D:\\programyMain\\yosys\\oss-cad-suite\\bin\\../share/yosys/techmap.v:583.21-583.22" *)
  wire [1:0] _39_;
  (* src = "../MODEL\\library_modules.v:16.10-16.15" *)
  wire s_EN1;
  (* src = "../MODEL\\library_modules.v:16.17-16.22" *)
  wire s_EN2;
  (* src = "../MODEL\\library_modules.v:14.23-14.27" *)
  reg [10:0] s_Q1;
  (* src = "../MODEL\\library_modules.v:15.18-15.25" *)
  reg s_VALID;
  (* src = "../MODEL\\library_modules.v:17.15-17.22" *)
  reg [1:0] s_state;
  assign _17_ = ~_15_;
  assign _18_ = ~_38_;
  assign _19_ = ~_14_;
  assign _20_ = _18_ & _37_;
  assign _21_ = ~(_17_ & _20_);
  assign _33_ = ~_21_;
  assign _30_ = ~(_38_ & _37_);
  assign _22_ = ~(_21_ & _30_);
  assign _34_ = ~(_14_ | _22_);
  assign _35_ = ~(_19_ | _22_);
  assign _31_ = _38_ | _37_;
  assign _23_ = _15_ & _20_;
  assign _24_ = ~(_16_ & _23_);
  assign _25_ = _15_ | _30_;
  assign _26_ = _16_ | _31_;
  assign _27_ = _25_ & _26_;
  assign _13_ = _24_ & _27_;
  assign _28_ = ~(_37_ & _36_);
  assign _29_ = _38_ & _28_;
  assign _32_ = ~(_23_ | _29_);
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[0] = s_Q1[0];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[1] = s_Q1[1];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[2] = s_Q1[2];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[3] = s_Q1[3];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[4] = s_Q1[4];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[5] = s_Q1[5];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[6] = s_Q1[6];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[7] = s_Q1[7];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[8] = s_Q1[8];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[9] = s_Q1[9];
  (* src = "../MODEL\\library_modules.v:37.5-39.25" *)
  always @*
    if (s_EN2) o_Q[10] = s_Q1[10];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[0] = i_D[0];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[1] = i_D[1];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[2] = i_D[2];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[3] = i_D[3];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[4] = i_D[4];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[5] = i_D[5];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[6] = i_D[6];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[7] = i_D[7];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[8] = i_D[8];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[9] = i_D[9];
  (* src = "../MODEL\\library_modules.v:33.5-35.25" *)
  always @*
    if (s_EN1) s_Q1[10] = i_D[10];
  (* src = "../MODEL\\library_modules.v:27.5-31.32" *)
  always @(posedge i_CLK, negedge i_RSTn)
    if (!i_RSTn) s_VALID <= 1'h0;
    else s_VALID <= i_VALID;
  (* src = "../MODEL\\library_modules.v:41.5-63.20" *)
  always @(posedge i_CLK, negedge i_RSTn)
    if (!i_RSTn) s_state[0] <= 1'h0;
    else if (_00_) s_state[0] <= _39_[0];
  (* src = "../MODEL\\library_modules.v:41.5-63.20" *)
  always @(posedge i_CLK, negedge i_RSTn)
    if (!i_RSTn) s_state[1] <= 1'h0;
    else if (_00_) s_state[1] <= _39_[1];
  assign _15_ = i_READY;
  assign _38_ = s_state[1];
  assign _37_ = s_state[0];
  assign _14_ = i_CLK;
  assign s_EN1 = _34_;
  assign s_EN2 = _35_;
  assign o_READY = _30_;
  assign o_VALID = _31_;
  assign _16_ = i_VALID;
  assign _00_ = _13_;
  assign _36_ = s_VALID;
  assign _39_[1] = _33_;
  assign _39_[0] = _32_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "../MODEL/alu.v:3.1-87.10" *)
module ALU(i_arg0, i_arg1, i_oper, o_Y, i_CLK, i_RSTn, i_VALID, o_READY, o_VALID, i_READY);
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  input [7:0] i_arg0;
  wire [7:0] i_arg0;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  input [7:0] i_arg1;
  wire [7:0] i_arg1;
  (* src = "../MODEL/alu.v:9.22-9.28" *)
  input [1:0] i_oper;
  wire [1:0] i_oper;
  (* src = "../MODEL/alu.v:11.29-11.32" *)
  output [10:0] o_Y;
  wire [10:0] o_Y;
  (* src = "../MODEL/alu.v:13.16-13.21" *)
  input i_CLK;
  wire i_CLK;
  (* src = "../MODEL/alu.v:14.16-14.22" *)
  input i_RSTn;
  wire i_RSTn;
  (* src = "../MODEL/alu.v:15.16-15.23" *)
  input i_VALID;
  wire i_VALID;
  (* src = "../MODEL/alu.v:16.17-16.24" *)
  output o_READY;
  wire o_READY;
  (* src = "../MODEL/alu.v:17.17-17.24" *)
  output o_VALID;
  wire o_VALID;
  (* src = "../MODEL/alu.v:18.16-18.23" *)
  input i_READY;
  wire i_READY;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  (* src = "../MODEL/alu.v:23.9-23.19" *)
  wire _229_;
  (* src = "../MODEL/alu.v:22.9-22.22" *)
  wire _230_;
  (* src = "../MODEL/alu.v:24.9-24.18" *)
  wire _231_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _232_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _233_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _234_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _235_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _236_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _237_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _238_;
  (* src = "../MODEL/alu.v:7.35-7.41" *)
  wire _239_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _240_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _241_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _242_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _243_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _244_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _245_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _246_;
  (* src = "../MODEL/alu.v:8.35-8.41" *)
  wire _247_;
  (* src = "../MODEL/alu.v:9.22-9.28" *)
  wire _248_;
  (* src = "../MODEL/alu.v:9.22-9.28" *)
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _474_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _475_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _476_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _477_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _478_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _479_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _480_;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire _481_;
  (* src = "../MODEL/alu.v:23.9-23.19" *)
  wire flag_carry;
  (* src = "../MODEL/alu.v:22.9-22.22" *)
  wire flag_overflow;
  (* src = "../MODEL/alu.v:24.9-24.18" *)
  wire flag_zero;
  (* src = "../MODEL/alu.v:21.28-21.36" *)
  wire [7:0] o_result;
  assign _405_ = ~_232_;
  assign _406_ = ~_249_;
  assign _407_ = ~_246_;
  assign _408_ = ~_235_;
  assign _409_ = ~_241_;
  assign _410_ = ~_242_;
  assign _411_ = ~_244_;
  assign _412_ = ~_247_;
  assign _413_ = ~_245_;
  assign _414_ = ~(_245_ & _243_);
  assign _415_ = _245_ ^ _243_;
  assign _416_ = ~(_247_ & _415_);
  assign _417_ = _247_ ^ _415_;
  assign _418_ = ~(_244_ & _417_);
  assign _419_ = _244_ ^ _417_;
  assign _420_ = ~(_242_ & _419_);
  assign _421_ = _242_ ^ _419_;
  assign _422_ = ~(_237_ & _239_);
  assign _423_ = _237_ ^ _239_;
  assign _424_ = ~(_241_ & _423_);
  assign _425_ = _241_ ^ _423_;
  assign _426_ = ~(_232_ & _233_);
  assign _427_ = _232_ ^ _233_;
  assign _428_ = ~(_235_ & _427_);
  assign _429_ = _235_ ^ _427_;
  assign _430_ = ~(_246_ & _429_);
  assign _431_ = _246_ ^ _429_;
  assign _432_ = ~(_425_ & _431_);
  assign _433_ = _425_ ^ _431_;
  assign _434_ = ~(_240_ & _433_);
  assign _435_ = _240_ ^ _433_;
  assign _436_ = ~(_421_ & _435_);
  assign _437_ = _421_ ^ _435_;
  assign _438_ = ~(_236_ & _437_);
  assign _439_ = _236_ ^ _437_;
  assign _440_ = ~(_238_ & _439_);
  assign _441_ = _238_ ^ _439_;
  assign _442_ = _234_ & _441_;
  assign _443_ = _234_ | _441_;
  assign _444_ = _248_ & _249_;
  assign _445_ = ~(_443_ & _444_);
  assign _446_ = _442_ | _445_;
  assign _447_ = _240_ & _232_;
  assign _448_ = ~(_248_ | _406_);
  assign _449_ = ~(_447_ & _448_);
  assign _450_ = _240_ & _405_;
  assign _451_ = _240_ ^ _232_;
  assign _452_ = ~(_406_ & _451_);
  assign _453_ = _449_ & _452_;
  assign _474_ = ~(_446_ & _453_);
  assign _454_ = ~(_438_ & _440_);
  assign _455_ = ~(_418_ & _420_);
  assign _456_ = ~(_434_ & _436_);
  assign _457_ = ~(_414_ & _416_);
  assign _458_ = ~(_422_ & _424_);
  assign _459_ = _457_ & _458_;
  assign _460_ = _457_ ^ _458_;
  assign _461_ = ~(_430_ & _432_);
  assign _462_ = ~(_426_ & _428_);
  assign _463_ = _461_ & _462_;
  assign _464_ = _461_ ^ _462_;
  assign _465_ = ~(_460_ & _464_);
  assign _466_ = _460_ ^ _464_;
  assign _467_ = ~(_456_ & _466_);
  assign _468_ = _456_ ^ _466_;
  assign _469_ = ~(_455_ & _468_);
  assign _470_ = _455_ ^ _468_;
  assign _471_ = ~(_454_ & _470_);
  assign _472_ = _454_ ^ _470_;
  assign _473_ = _442_ | _472_;
  assign _250_ = ~(_442_ & _472_);
  assign _251_ = _444_ & _473_;
  assign _252_ = ~(_250_ & _251_);
  assign _253_ = _233_ & _241_;
  assign _254_ = _233_ ^ _241_;
  assign _255_ = ~(_248_ | _249_);
  assign _256_ = _447_ & _254_;
  assign _257_ = _447_ ^ _254_;
  assign _258_ = ~(_255_ & _257_);
  assign _259_ = ~(_448_ & _253_);
  assign _260_ = _450_ | _254_;
  assign _261_ = _248_ & _406_;
  assign _262_ = _450_ ^ _254_;
  assign _263_ = ~(_261_ & _262_);
  assign _264_ = _258_ & _259_;
  assign _265_ = _263_ & _264_;
  assign _475_ = ~(_252_ & _265_);
  assign _266_ = _253_ | _256_;
  assign _267_ = ~(_242_ & _234_);
  assign _268_ = _242_ ^ _234_;
  assign _269_ = ~(_266_ & _268_);
  assign _270_ = _266_ | _268_;
  assign _271_ = ~(_269_ & _270_);
  assign _272_ = ~(_255_ & _271_);
  assign _273_ = ~(_471_ & _250_);
  assign _274_ = ~(_467_ & _469_);
  assign _275_ = ~(_459_ & _463_);
  assign _276_ = ~(_459_ | _463_);
  assign _277_ = ~(_465_ & _276_);
  assign _278_ = _275_ & _277_;
  assign _279_ = ~(_274_ & _278_);
  assign _280_ = _274_ ^ _278_;
  assign _281_ = ~(_273_ & _280_);
  assign _282_ = _273_ | _280_;
  assign _283_ = _444_ & _282_;
  assign _284_ = ~(_281_ & _283_);
  assign _285_ = ~(_233_ & _409_);
  assign _286_ = _260_ & _285_;
  assign _287_ = ~(_268_ & _286_);
  assign _288_ = _268_ | _286_;
  assign _289_ = _261_ & _287_;
  assign _290_ = ~(_288_ & _289_);
  assign _291_ = ~(_248_ | _267_);
  assign _292_ = ~(_255_ | _291_);
  assign _293_ = _290_ & _292_;
  assign _294_ = ~(_284_ & _293_);
  assign _476_ = _272_ & _294_;
  assign _295_ = _279_ & _281_;
  assign _296_ = ~(_275_ & _295_);
  assign _297_ = ~(_275_ | _281_);
  assign _298_ = ~(_444_ & _296_);
  assign _299_ = ~(_297_ | _298_);
  assign _300_ = _235_ & _243_;
  assign _301_ = _235_ | _243_;
  assign _302_ = _235_ ^ _243_;
  assign _303_ = ~(_410_ & _234_);
  assign _304_ = _288_ & _303_;
  assign _305_ = _302_ ^ _304_;
  assign _306_ = ~(_261_ & _305_);
  assign _307_ = ~(_448_ & _300_);
  assign _308_ = ~(_267_ & _269_);
  assign _309_ = _302_ ^ _308_;
  assign _310_ = ~(_255_ & _309_);
  assign _311_ = _307_ & _310_;
  assign _312_ = ~(_306_ & _311_);
  assign _477_ = _299_ | _312_;
  assign _313_ = ~(_444_ & _297_);
  assign _314_ = _236_ & _244_;
  assign _315_ = ~(_236_ & _244_);
  assign _316_ = _236_ ^ _244_;
  assign _317_ = ~(_408_ & _243_);
  assign _318_ = _408_ | _243_;
  assign _319_ = ~(_304_ & _318_);
  assign _320_ = ~(_317_ & _319_);
  assign _321_ = ~(_316_ & _320_);
  assign _322_ = _316_ | _320_;
  assign _323_ = _261_ & _321_;
  assign _324_ = ~(_322_ & _323_);
  assign _325_ = ~(_448_ & _314_);
  assign _326_ = _301_ & _308_;
  assign _327_ = _300_ | _326_;
  assign _328_ = ~(_316_ & _327_);
  assign _329_ = _316_ | _327_;
  assign _330_ = _255_ & _329_;
  assign _331_ = ~(_328_ & _330_);
  assign _332_ = _325_ & _331_;
  assign _333_ = _324_ & _332_;
  assign _478_ = ~(_313_ & _333_);
  assign _334_ = _237_ & _245_;
  assign _335_ = ~(_237_ & _245_);
  assign _336_ = _237_ | _245_;
  assign _337_ = _335_ & _336_;
  assign _338_ = ~(_236_ & _411_);
  assign _339_ = _322_ & _338_;
  assign _340_ = _337_ | _339_;
  assign _341_ = _337_ ^ _339_;
  assign _342_ = ~(_261_ & _341_);
  assign _343_ = ~(_315_ & _328_);
  assign _344_ = _337_ ^ _343_;
  assign _345_ = ~(_255_ & _344_);
  assign _346_ = ~(_448_ & _334_);
  assign _347_ = _345_ & _346_;
  assign _479_ = ~(_342_ & _347_);
  assign _348_ = ~(_238_ & _246_);
  assign _349_ = _238_ ^ _246_;
  assign _350_ = ~(_336_ & _343_);
  assign _351_ = ~(_335_ & _350_);
  assign _352_ = ~(_349_ & _351_);
  assign _353_ = _349_ | _351_;
  assign _354_ = ~(_352_ & _353_);
  assign _355_ = _255_ & _354_;
  assign _356_ = ~(_237_ & _413_);
  assign _357_ = _340_ & _356_;
  assign _358_ = _349_ | _357_;
  assign _359_ = ~(_349_ & _357_);
  assign _360_ = _261_ & _359_;
  assign _361_ = ~(_358_ & _360_);
  assign _362_ = ~(_248_ | _348_);
  assign _363_ = ~(_255_ | _362_);
  assign _364_ = _361_ & _363_;
  assign _480_ = ~(_355_ | _364_);
  assign _365_ = _239_ & _247_;
  assign _366_ = ~(_239_ & _247_);
  assign _367_ = _239_ | _247_;
  assign _368_ = _366_ & _367_;
  assign _369_ = ~(_348_ & _352_);
  assign _370_ = ~(_238_ & _407_);
  assign _371_ = _358_ & _370_;
  assign _372_ = ~(_358_ & _370_);
  assign _373_ = ~(_448_ & _365_);
  assign _374_ = ~(_368_ & _371_);
  assign _375_ = ~(_239_ & _412_);
  assign _376_ = _239_ | _412_;
  assign _377_ = _372_ & _376_;
  assign _378_ = ~(_372_ & _376_);
  assign _379_ = ~(_375_ & _377_);
  assign _380_ = _261_ & _379_;
  assign _381_ = ~(_374_ & _380_);
  assign _382_ = _368_ | _369_;
  assign _383_ = ~(_368_ & _369_);
  assign _384_ = _255_ & _383_;
  assign _385_ = ~(_382_ & _384_);
  assign _386_ = _373_ & _385_;
  assign _387_ = _381_ & _386_;
  assign _481_ = ~_387_;
  assign _388_ = _475_ | _480_;
  assign _389_ = ~(_477_ | _388_);
  assign _390_ = ~(_474_ | _479_);
  assign _391_ = ~(_387_ & _390_);
  assign _392_ = _478_ | _391_;
  assign _393_ = ~(_476_ | _392_);
  assign _231_ = _389_ & _393_;
  assign _394_ = ~(_371_ & _375_);
  assign _395_ = _261_ & _378_;
  assign _396_ = ~(_394_ & _395_);
  assign _397_ = ~(_367_ & _369_);
  assign _398_ = _365_ | _369_;
  assign _399_ = _255_ & _398_;
  assign _400_ = ~(_397_ & _399_);
  assign _230_ = ~(_396_ & _400_);
  assign _401_ = ~(_375_ & _395_);
  assign _402_ = ~(_366_ & _369_);
  assign _403_ = _255_ & _367_;
  assign _404_ = ~(_402_ & _403_);
  assign _229_ = ~(_401_ & _404_);
  (* src = "../MODEL/alu.v:74.7-85.6" *)
  \$paramod\cpreg\WIDTH=s32'00000000000000000000000000001011  u_preg (
    .i_CLK(i_CLK),
    .i_D({ o_result, flag_overflow, flag_carry, flag_zero }),
    .i_READY(i_READY),
    .i_RSTn(i_RSTn),
    .i_VALID(i_VALID),
    .o_Q(o_Y),
    .o_READY(o_READY),
    .o_VALID(o_VALID)
  );
  assign _240_ = i_arg1[0];
  assign _232_ = i_arg0[0];
  assign _248_ = i_oper[0];
  assign _249_ = i_oper[1];
  assign _238_ = i_arg0[6];
  assign _236_ = i_arg0[4];
  assign _246_ = i_arg1[6];
  assign _235_ = i_arg0[3];
  assign _233_ = i_arg0[1];
  assign _241_ = i_arg1[1];
  assign _237_ = i_arg0[5];
  assign _239_ = i_arg0[7];
  assign _242_ = i_arg1[2];
  assign _244_ = i_arg1[4];
  assign _247_ = i_arg1[7];
  assign _245_ = i_arg1[5];
  assign _243_ = i_arg1[3];
  assign _234_ = i_arg0[2];
  assign o_result[0] = _474_;
  assign o_result[1] = _475_;
  assign o_result[2] = _476_;
  assign o_result[3] = _477_;
  assign o_result[4] = _478_;
  assign o_result[5] = _479_;
  assign o_result[6] = _480_;
  assign o_result[7] = _481_;
  assign flag_zero = _231_;
  assign flag_overflow = _230_;
  assign flag_carry = _229_;
endmodule
